version: "3.7"
services:
  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    ports:
      - "9100:9100"
    command:
      - '--path.rootfs=/host'
    pid: host
    restart: unless-stopped
    volumes:
      - '/:/host:ro,rslave'
  cadvisor:
#    image: google/cadvisor:latest
    image: gcr.io/cadvisor/cadvisor:v0.46.0
    container_name: cadvisor
    ports:
      - "8181:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    devices:
#      - /dev/kmsg
      - "/dev/kmsg:/dev/kmsg"
    privileged: true
    restart: unless-stopped
  promtail:
    image: grafana/promtail:2.9.3
    container_name: promtail
    volumes:
#      - /home/supervisor/servtomcat/datos/logs-tomcat-internacion:/var/log/tomcat-internacion
      - /var/log:/var/log      
      - ./promtail/config.yml:/etc/promtail/config.yml
#      - ./pgbouncer/pgbouncer.log:/var/log/pgbouncer.log
    command: -config.file=/etc/promtail/config.yml
    restart: unless-stopped